name: 'steam_dataset_2025'
version: '1.0.0'
profile: 'steam_dataset_2025'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  steam_dataset_2025:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
